type: module
name: UD config JSON source migration
description: 'Example configuration JSON source migration. Learn more at <a href="https://understanddrupal.com/migrations" title="Drupal Migrations">https://understanddrupal.com/migrations</a>.'
package: Understand Drupal
core: 8.x
dependencies:
  - drupal:migrate
  - entity_reference_revisions:entity_reference_revisions
  - migrate_plus:migrate_plus
  - paragraphs:paragraphs
  - ud_migrations_paragraph_config:ud_migrations_paragraph_config
