type: module
name: UD configuration group migration (JSON source)
description: 'Example migration for configuration group with JSON source. Learn more at <a href="https://understanddrupal.com/migrations" title="Drupal Migrations">https://understanddrupal.com/migrations</a>.'
package: Understand Drupal
core: 8.x
dependencies:
  - drupal:migrate
  - entity_reference_revisions:entity_reference_revisions
  - migrate_plus:migrate_plus
  # Migrate Tools is set as dependency to use the user interface it provides to
  # execute migrations. It also exposes Drush commands for executing migrations.
  - migrate_tools:migrate_tools
  - paragraphs:paragraphs
  - ud_migrations_paragraph_config:ud_migrations_paragraph_config
